### ISSUE TITLE
Extra closing head tag

### ISSUE THREAD

**Issue by geekayush** [ncs-jss/Webcomb#3]
I cannot see JavaScript working when written in the Script section. However, downloaded file is running fine. I can also see an extra closing head tag just before closing HTML tag. Maybe this is creating issues in running scripts on the platform.

![Screenshot 2020-05-12 at 1 55 35 PM](https://user-images.githubusercontent.com/22499864/81660348-442c2c80-9458-11ea-9dcc-ed1d65b5805d.png)

**Comment by rajat2502** [comment]
![image](https://user-images.githubusercontent.com/42200276/81670556-6ed0b200-9465-11ea-8c0d-dc5296ab89da.png)
It was working when I tried it. Also, there was no such extra `head` tag in the file. 
![image](https://user-images.githubusercontent.com/42200276/81670901-ed2d5400-9465-11ea-8d3c-89100ebe34a4.png) 
(this is the downloaded file)

Let me know if you still face this error or maybe share the code so that I can get a wider view of the problem.

**Comment by geekayush** [comment]
Scripts didn't work for me when I wrote it in the JS section of the playground.
### HTML
```
<input type="submit" value="Click" onclick="say()"/>
```
### JS
```Javascript
function say(){
    alert();
}
```
This should have prompted me on clicking the button. But click never responds.
Although, the same file when ran after downloading works.

However, If I change my code to:
### HTML
```
<input type="submit" value="Click" onclick="alert()"/>
```
It works!

Regarding the extra closing tag, see the second last line of the document. It's there.

**Comment by rajat2502** [comment]
> Regarding the extra closing tag, see the second last line of the document. It's there.

Yeah, that's an issue...I have removed the extra `head` tag now.

**Comment by rajat2502** [comment]
> Scripts didn't work for me when I wrote it in the JS section of the playground.
> 
> ### HTML
> ```
> <input type="submit" value="Click" onclick="say()"/>
> ```
> 
> ### JS
> ```js
> function say(){
>     alert();
> }
> ```
> 
> This should have prompted me on clicking the button. But click never responds.
> Although, the same file when ran after downloading works.
> 
> However, If I change my code to:
> 
> ### HTML
> ```
> <input type="submit" value="Click" onclick="alert()"/>
> ```
> 
> It works!

I think this is something related to the browser the same code is working fine in my browser. Also, the downloaded file is working as expected.
![image](https://user-images.githubusercontent.com/42200276/81696870-1c51be80-9482-11ea-85dc-144b60f65bac.png)

Both the above versions are working fine in my browser.
I have tried on Chrome and Firefox and it's working fine on both.

**Comment by geekayush** [comment]
I've got more insights. The problem is with the naming of the function.
Can you try this once?
### HTML
```
<input type="submit" value="Click" onclick="convert()"/>
```
### JS
```Javascript
function convert(){
	alert();
}
```
It will throw and error.

**Comment by rajat2502** [comment]
That also is working fine in my system.
![image](https://user-images.githubusercontent.com/42200276/81708159-adc72d80-948e-11ea-9278-988e8ba85c48.png)

**Comment by geekayush** [comment]
I refreshed the page and it is now working fine. It might be cache. 😄
